const actions = {
  USER_REGISTER: "USER_REGISTER",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILED: "USER_REGISTER_FAILED",

  USER_SIGNIN: "USER_SIGNIN",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILED: "USER_SIGNIN_FAILED",

  USER_SIGNOUT: "USER_SIGNOUT",
  USER_SIGNOUT_SUCCESS: "USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAILED: "USER_SIGNOUT_FAILED",

  POSTS_GET: "POSTS_GET",
  POSTS_GET_SUCCESS: "POST_GET_SUCCESS",
  POSTS_GET_FAILED: "POSTS_GET_FAILED",

  CREATE_POSTS: "CREATE_POSTS",
  CREATE_POSTS_SUCCESS: "CREATE_POSTS_SUCCESS",
  CREATE_POSTS_FAILED: "CREATE_POSTS_FAILED",

  DELETE_POSTS: "DELETE_POSTS",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_FAILED: "DELETE_POSTS_FAILED",

  EDIT_POSTS: "EDIT_POSTS",
  EDIT_POSTS_SUCCESS: "EDIT_POSTS_SUCCESS",
  EDIT_POSTS_FAILED: "EDIT_POSTS_FAILED",

  VALIDATE_USER: "VALIDATE_USER",
  VALIDATE_USER_SUCCESS: "VALIDATE_USER_SUCCESS",
  VALIDATE_USER_FAILED: "VALIDATE_USER_FAILED",

  DRAWER_OPEN: "DRAWER_OPEN",

  SHOW_CREATED_POSTS: "SHOW_CREATED_POSTS",
  SHOW_CREATED_POSTS_SUCCESS: "SHOW_CREATED_POSTS_SUCCESS",
  SHOW_CREATED_POSTS_FAILED: "SHOW_CREATED_POSTS_FAILED",

  DATA_TO_BE_EDITED: "DATA_TO_BE_EDITED",

  PUBLISH_POSTS: "PUBLISH_POSTS",
  PUBLISH_POSTS_SUCCESS: "PUBLISH_POSTS_SUCCESS",
  PUBLISH_POSTS_FAILED: "PUBLISH_POSTS_FAILED",

  GET_PUBLISHED_POSTS: "GET_PUBLISHED_POSTS",
  GET_PUBLISHED_POSTS_SUCCESS: "GET_PUBLISHED_POSTS_SUCCESS",
  GET_PUBLISHED_POSTS_FAILED: "GET_PUBLISHED_POSTS_FAILED",

  SHOW_PUBLISHED_POSTS: "SHOW_PUBLISHED_POSTS",
  SHOW_PUBLISHED_POSTS_SUCCESS: "SHOW_PUBLISHED_POSTS_SUCCESS",
  SHOW_PUBLISHED_POSTS_FAILED: "SHOW_PUBLISHED_POSTS_FAILED",

  CREATE_COMMENT: "CREATE_COMMENT",
  CREATE_COMMENT_SUCCESS: "CREATE_COMMENT_SUCCESS",
  CREATE_COMMENT_FAILED: "CREATE_COMMENT_FAILED",

  DELETE_COMMENT: "DELETE_COMMENT",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILED: "DELETE_COMMENT_FAILED",

  EDIT_COMMENT: "EDIT_COMMENT",
  EDIT_COMMENT_SUCCESS: "EDIT_COMMENT_SUCCESS",
  EDIT_COMMENT_FAILED: "EDIT_COMMENT_FAILED",

  COMMENT_EDIT_DATA: "COMMENT_EDIT_DATA",

  OFFSET_INCREMENT: "OFFSET_INCREMENT",

  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILED: "UPDATE_PROFILE_FAILED",

  RESET_OFFSET_VALUE: "RESET_OFFSET_VALUE",

  SEARCH_FILTER: "SEARCH_FILTER",
  SEARCH_FILTER_SUCCESS: "SEARCH_FILTER_SUCCESS",
  SEARCH_FILTER_FAILED: "SEARCH_FILTER_FAILED",
};

export default actions;
